[options]
cwbvh = true
max_depth = 5
spp = 10
# shading = "basic" # Surfaces hit more often are brighter
shading = "diffuse" # Diffuse shading
# shading = "ao" # AO shading
sort = false # Sort rays

#---------------------------------------------------------------------------------------------------
# Teapot
#---------------------------------------------------------------------------------------------------
[model]
name = "teapot"
output = "teapot.jpg"

[camera]
resolution = [1280, 720]
position = [0.0, 40.0, 150.0]
target = [0.0, 40.0, 0.0]
up = [0.0, 1.0, 0.0]
fovy = 45.0

#---------------------------------------------------------------------------------------------------
# Dragon
#---------------------------------------------------------------------------------------------------
# [model]
# name = "dragon"
# output = "dragon.jpg"

# [camera]
# resolution = [1280, 720]
# position = [-0.8, 0.1, -0.8]
# target = [0.0, 0.0, 0.0]
# up = [0.0, 1.0, 0.0]
# fovy = 45.0

#---------------------------------------------------------------------------------------------------
# Sibenik
#---------------------------------------------------------------------------------------------------
# [model]
# name = "sibenik"
# output = "sibenik.jpg"

# [camera]
# resolution = [1280, 720]
# position = [-5.0, -12.0, 0.0]
# target = [0.0, -12.0, 0.0]
# up = [0.0, 1.0, 0.0]
# fovy = 45.0

#---------------------------------------------------------------------------------------------------
# Hairball
#---------------------------------------------------------------------------------------------------
# [model]
# name = "hairball"
# output = "hairball.jpg"

# [camera]
# resolution = [1280, 720]
# position = [0.0, 0.0, 9.0]
# target = [0.0, 0.0, 0.0]
# up = [0.0, 1.0, 0.0]
# fovy = 45.0

#---------------------------------------------------------------------------------------------------
# CrySponza
#---------------------------------------------------------------------------------------------------
# [model]
# name = "sponza"
# output = "sponza.jpg"

# [camera]
# resolution = [1280, 720]
# position = [1220.0, 700.0, -170.0]
# target = [0.0, 400.0, 0.0]
# up = [0.0, 1.0, 0.0]
# fovy = 45.0

#---------------------------------------------------------------------------------------------------
# Bunny
#---------------------------------------------------------------------------------------------------
# [model]
# name = "bunny"
# output = "bunny.jpg"

# [camera]
# resolution = [1280, 720]
# position = [0.0, 0.7, 2.5]
# target = [0.0, 0.7, 0.0]
# up = [0.0, 1.0, 0.0]
# fovy = 45.0
