[options]
cwbvh = false
max_depth = 5
spp = 10
shading = "diffuse" # Diffuse shading
sort = false # Sort rays

#---------------------------------------------------------------------------------------------------
# Sibenik
#---------------------------------------------------------------------------------------------------
[model]
name = "sibenik"
output = "sibenik2.jpg"

[camera]
resolution = [1280, 720]
position = [14.0, -8.6, 8.0]
target = [4.4, -12.0, 0.5]
up = [0.0, 1.0, 0.0]
fovy = 45.0
